name: app-test

on:
  push:
    branches:
      - develop
      - master
  pull_request:

defaults:
  run:
    working-directory: .

jobs:
  apptests:
    name: Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Clean db before tests
        run: delete_all_nodes
      - name: Run mvn test
        run: mvn test
      - name: Clean db after tests
        run: delete_all_nodes